// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbmTY-F-rzPKv5reEY8HWJhj0p4P4C6y4',
    appId: '1:850558662604:web:dc2a85d6c9e3a9c1044f69',
    messagingSenderId: '850558662604',
    projectId: 'bitebox-da3ef',
    authDomain: 'bitebox-da3ef.firebaseapp.com',
    storageBucket: 'bitebox-da3ef.firebasestorage.app',
    measurementId: 'G-96NNVDZPDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTqudvJSewPFjiCYyTWFOS_jaDmnYrgpI',
    appId: '1:850558662604:android:d04a5a206658e05f044f69',
    messagingSenderId: '850558662604',
    projectId: 'bitebox-da3ef',
    storageBucket: 'bitebox-da3ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtFsVarnnQuzfgdDCuc3cag5DTVVlmmdI',
    appId: '1:850558662604:ios:33f0f3f2666b8e64044f69',
    messagingSenderId: '850558662604',
    projectId: 'bitebox-da3ef',
    storageBucket: 'bitebox-da3ef.firebasestorage.app',
    iosBundleId: 'com.example.bitebox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtFsVarnnQuzfgdDCuc3cag5DTVVlmmdI',
    appId: '1:850558662604:ios:33f0f3f2666b8e64044f69',
    messagingSenderId: '850558662604',
    projectId: 'bitebox-da3ef',
    storageBucket: 'bitebox-da3ef.firebasestorage.app',
    iosBundleId: 'com.example.bitebox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbmTY-F-rzPKv5reEY8HWJhj0p4P4C6y4',
    appId: '1:850558662604:web:e867a533318dfd75044f69',
    messagingSenderId: '850558662604',
    projectId: 'bitebox-da3ef',
    authDomain: 'bitebox-da3ef.firebaseapp.com',
    storageBucket: 'bitebox-da3ef.firebasestorage.app',
    measurementId: 'G-9T3MGP4ZX7',
  );

}